name = "polished-salad-019b"
main = "worker.js"
compatibility_date = "2026-08-01"

# Telegram bot token gibi gizli bilgileri buraya YAZMA.
# Onları Cloudflare panelinden "Settings > Variables" kısmından ekleyeceksin.

[[kv_namespaces]]
binding = "VERI"
id = "90aa260cfa1343e3a91bf96ea9615958"
